second iteration
BubuntuClu/cookbook pull request #12
Opened 2017-04-05 10:13 UTC by BubuntuClu

2017-04-07 13:03 UTC, vkurennov requested changes

2017-04-07 13:03 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +    ##TODO (вопрос 1) как можно сделать по-хорошему?
Что-то я вообще не понял сути этого кода. Зачем делать find, если результат нигде не используется. И где определен метод `recipe_send_to_draft_path`? почему не в текущем контроллере?

2017-04-07 13:03 UTC, vkurennov commented on app/controllers/recipes_controller.rb
> +  def send_to_publish
Что если мы сразу вызовем этот метод, в обход отправки на модерацию? У тебя слишком много бизнес-логики в контроллере получается. Надо всю схему изменения статусов вынести в модель, а в контроллере должен быть один метод, который бы менял статус, а на какой именно - решает модель.
Может быть, тут будет полезен гем [state_machine](https://github.com/pluginaweek/state_machine)

2017-04-07 13:03 UTC, vkurennov commented on app/models/recipe.rb
> +  def is_draft?
А зачем делать методы с приставкой is, если есть обычные? Ну и если уж так хочется, то лучше использовать alias

2017-04-07 13:03 UTC, vkurennov commented on config/routes.rb
> +    get 'send_to_draft', to: 'recipes#send_to_draft'
get-запросы не должны менять состояние объектов

2017-04-07 13:37 UTC, BubuntuClu commented on app/controllers/comments_controller.rb
> +    ##TODO (вопрос 1) как можно сделать по-хорошему?
Мы находим рецепт и к нему создаем комментарий.
После этого передаем управление в экшн другого контроллера через путь.

2017-04-07 13:37 UTC, BubuntuClu commented on config/routes.rb
> +    get 'send_to_draft', to: 'recipes#send_to_draft'
да, я знаю, я про это и хотел спросить в вопросе "как можно сделать по-хорошему? ")

2017-04-12 09:34 UTC, BubuntuClu commented on app/models/recipe.rb
> +  def is_draft?
+

2017-04-12 16:37 UTC, vkurennov requested changes

2017-04-12 16:37 UTC, vkurennov commented on app/models/state_controller.rb
> +class StateController
Это не контроллер в архитектуре MVC, так что название не очень удачное.
И почему бы не хранить эту логику в самом рецепте? Были бы инстанс-методы у рецепта, и их бы и вызывали у него.

2017-04-17 11:26 UTC, vkurennov requested changes

2017-04-17 11:26 UTC, vkurennov commented on app/controllers/recipes_controller.rb
> +  def send_to_moderation
Было бы здорово провернуть такой сценарий:
 роутинг был бы вида `/recipes/:id/[:moderation, :publish, :draft]` (один из вариантов)
 в контроллере был бы один метод, который бы обрабатывал такой запрос
 этот метод по имени экшена вызывал бы через send нужные метод у модели.

2017-04-17 11:26 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      self.update!(rating: sum )
Это дублирование с методом vote_up, можно вообще все вынести в один метод и только параметром передавть значение голоса.

2017-04-17 11:26 UTC, vkurennov commented on app/views/recipes/_recipe.html.haml
> +    - user = User.find(recipe.user_id)
Никогда не делай поиск в видах, как только это увидит потенциальный работодатель, сразу откажет. Вообще запросов и вычислений не должно быть в видах.

Да и вообще, зачем загружать через find, когда есть ассоциации?

2017-04-17 11:26 UTC, vkurennov commented on app/views/votes/_vote.html.haml
> +  - vote_button = (obj.voted_for(current_user) == 0  ) ? "" : "hidden"
Сравнение тут не красиво выглядит, сделай метод-предикат для этого у юзера или голоса.

2017-04-17 14:56 UTC, BubuntuClu commented on app/views/recipes/_recipe.html.haml
> +    - user = User.find(recipe.user_id)
да, это я что-то дикую хрень написал

2017-04-17 15:50 UTC, BubuntuClu commented on app/views/recipes/_recipe.html.haml
> +    - user = User.find(recipe.user_id)
+

2017-04-17 16:00 UTC, BubuntuClu commented on app/models/concerns/votable.rb
> +      self.update!(rating: sum )
+

2017-04-17 17:23 UTC, BubuntuClu commented on app/controllers/recipes_controller.rb
> +  def send_to_moderation
+

2017-04-17 17:29 UTC, BubuntuClu commented on app/views/votes/_vote.html.haml
> +  - vote_button = (obj.voted_for(current_user) == 0  ) ? "" : "hidden"
+

2017-04-18 07:33 UTC, vkurennov requested changes

2017-04-18 07:33 UTC, vkurennov commented on app/controllers/recipes_controller.rb
> +    @recipe.send("set_to_#{params[:state]}", params[:comment] ||= nil)
А смысл делать `||= nil`, если и так `params[:comment]` вернет `nil`, если не был передан?

2017-04-18 07:33 UTC, vkurennov commented on app/controllers/recipes_controller.rb
> +  def state_handler
Название метода не очень понятное. Лучше что-то вроде `set_state` или `update_state`

2017-04-18 07:33 UTC, vkurennov commented on app/controllers/recipes_controller.rb
> +  def state_handler
И еще момент, тут ведь должна быть проверка прав, потому что на модерацию может отправить только автор, а принять/отклонить - только модератор/админ. А где эта проверка? `authorize_resource` у тебя закомментарен почему-то и ability в этом PR нет.

Хорошо бы тут как раз написать тест контроллера на этот метод и проверить, что нужные действия может выполнить только юзер с нужными правами.

2017-04-18 10:41 UTC, BubuntuClu commented on app/controllers/recipes_controller.rb
> +    @recipe.send("set_to_#{params[:state]}", params[:comment] ||= nil)
+

2017-04-20 08:04 UTC, vkurennov approved these changes

2017-05-03 09:14 UTC, merged